2017-06-13 10:06:28,940 INFO TC57_kill_lead_mon_on_multiMon.py [line:29] 
This test case will do the following steps:
1. start IO on 10 images with randwrite and verify
2. login the leader monitor, and kill the mon process
3. check cluster status, Io status and cluster quorum status
4. login the new leader monitor, and kill the mon process
5. check cluster status, Io status and cluster quorum status
6. start the first killed monitor
7. check cluster status, does the leader monitor will be back????
8. start the first killed monitor
9. check cluster status, does the leader monitor will be back????

2017-06-13 10:06:32,624 INFO monitors.py [line:126]    "quorum_leader_name": "taheo125",
stdin: is not a tty

2017-06-13 10:06:32,625 INFO monitors.py [line:129]    "quorum_leader_name": "taheo125",
2017-06-13 10:06:32,625 INFO TC57_kill_lead_mon_on_multiMon.py [line:32] start to check cluster status before case running
2017-06-13 10:06:34,631 INFO cluster.py [line:211] execute command is sudo -i ceph -s
2017-06-13 10:06:35,009 INFO cluster.py [line:213]    cluster c1b31c6e-ebc7-4c97-98ec-d59964f99e42
     health HEALTH_WARN
            1 mons down, quorum 0,2 taheo125,tahoe127
     monmap e3: 3 mons at {taheo125=192.168.40.125:6789/0,tahoe126=192.168.40.126:6789/0,tahoe127=192.168.40.127:6789/0}
            election epoch 62, quorum 0,2 taheo125,tahoe127
     osdmap e429: 18 osds: 18 up, 18 in
            flags sortbitwise,require_jewel_osds,require_kraken_osds
      pgmap v50968: 3216 pgs, 13 pools, 1498 GB data, 375 kobjects
            2055 GB used, 4134 GB / 6189 GB avail
                3216 active+clean
  client io 164 MB/s rd, 21109 op/s rd, 0 op/s wr
stdin: is not a tty

2017-06-13 10:06:35,010 INFO cluster.py [line:238] PG number is 3216
2017-06-13 10:06:35,010 INFO cluster.py [line:239] usefull PG number is 3216
2017-06-13 10:06:35,010 INFO TC57_kill_lead_mon_on_multiMon.py [line:35] health status is OK
2017-06-13 10:06:37,014 INFO TC57_kill_lead_mon_on_multiMon.py [line:43] 
Step1: Check IO from clients
2017-06-13 10:06:37,458 INFO client.py [line:172] ['oot      33365      1  0 Jun12 ?        00:00:00 sudo -i fio -direct=1 -iodepth_batch_complete=1 -ioengine=rbd -clientname=client100 -pool=reliablityTestPool -rbdname=client100rbdImg2 -rw=randwrite -bs=8K -size=300G -norandommap=1 -randrepeat=0 -verify=md5 -verify_fatal=1 -verify_dump=1 -do_verify=1 -overwrite=1 -iodepth=256 -name=client100rbdImg2', 'root      33366  33365 82 Jun12 ?        01:57:33 fio -direct=1 -iodepth_batch_complete=1 -ioengine=rbd -clientname=client100 -pool=reliablityTestPool -rbdname=client100rbdImg2 -rw=randwrite -bs=8K -size=300G -norandommap=1 -randrepeat=0 -verify=md5 -verify_fatal=1 -verify_dump=1 -do_verify=1 -overwrite=1 -iodepth=256 -name=client100rbdImg2', 'root      33436      1  0 Jun12 ?        00:00:00 sudo -i fio -direct=1 -iodepth_batch_complete=1 -ioengine=rbd -clientname=client100 -pool=reliablityTestPool -rbdname=client100rbdImg3 -rw=randwrite -bs=8K -size=400G -norandommap=1 -randrepeat=0 -verify=md5 -verify_fatal=1 -verify_dump=1 -do_verify=1 -overwrite=1 -iodepth=256 -name=client100rbdImg3', 'root      33439  33436 96 Jun12 ?        02:17:21 fio -direct=1 -iodepth_batch_complete=1 -ioengine=rbd -clientname=client100 -pool=reliablityTestPool -rbdname=client100rbdImg3 -rw=randwrite -bs=8K -size=400G -norandommap=1 -randrepeat=0 -verify=md5 -verify_fatal=1 -verify_dump=1 -do_verify=1 -overwrite=1 -iodepth=256 -name=client100rbdImg3', 'root      33508      1  0 Jun12 ?        00:00:00 sudo -i fio -direct=1 -iodepth_batch_complete=1 -ioengine=rbd -clientname=client100 -pool=reliablityTestPool -rbdname=client100rbdImg4 -rw=randwrite -bs=8K -size=500G -norandommap=1 -randrepeat=0 -verify=md5 -verify_fatal=1 -verify_dump=1 -do_verify=1 -overwrite=1 -iodepth=256 -name=client100rbdImg4', 'root      33510  33508 99 Jun12 ?        02:40:47 fio -direct=1 -iodepth_batch_complete=1 -ioengine=rbd -clientname=client100 -pool=reliablityTestPool -rbdname=client100rbdImg4 -rw=randwrite -bs=8K -size=500G -norandommap=1 -randrepeat=0 -verify=md5 -verify_fatal=1 -verify_dump=1 -do_verify=1 -overwrite=1 -iodepth=256 -name=client100rbdImg4', 'denali    92967  92966  0 02:06 ?        00:00:00 bash -c sudo -i ps -ef | grep fio ', 'denali    92969  92967  0 02:06 ?        00:00:00 grep fio', 'stdin: is not a tty', '']
2017-06-13 10:06:37,458 INFO client.py [line:174] IO is running
2017-06-13 10:07:37,492 INFO TC57_kill_lead_mon_on_multiMon.py [line:51] 
Step2: kill leader mon 10 times
2017-06-13 10:07:37,493 INFO monitors.py [line:55] mon is  taheo125
2017-06-13 10:07:37,493 INFO monitors.py [line:56] execute command is sudo -i stop ceph-mon id=taheo125 & sleep 5
2017-06-13 10:07:42,728 ERROR monitors.py [line:61] Error when shutdown mon taheo125
2017-06-13 10:07:42,729 ERROR monitors.py [line:62] sudo -i stop ceph-mon id=taheo125 & sleep 5
2017-06-13 10:07:42,729 ERROR monitors.py [line:63] tdin: is not a tty
stop: Unknown instance: ceph/taheo125

2017-06-13 10:07:42,729 INFO monitors.py [line:68] mon is  taheo125
2017-06-13 10:07:42,729 INFO monitors.py [line:69] execute command is sudo -i ceph-mon -i taheo125 & sleep 30
2017-06-13 10:08:12,913 ERROR monitors.py [line:75] Error when start mon taheo125
2017-06-13 10:08:12,914 ERROR monitors.py [line:76] sudo -i ceph-mon -i taheo125 & sleep 30
2017-06-13 10:08:12,914 ERROR monitors.py [line:77] tdin: is not a tty
2017-06-13 10:07:46.543882 7f6d01bee4c0 -1 asok(0x7f6cfe1351c0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-mon.taheo125.asok': (17) File exists
IO error: lock /var/lib/ceph/mon/ceph-taheo125/store.db/LOCK: Resource temporarily unavailable
2017-06-13 10:07:46.553269 7f6d01bee4c0 -1 error opening mon data directory at '/var/lib/ceph/mon/ceph-taheo125': (22) Invalid argument

2017-06-13 10:08:12,914 INFO monitors.py [line:55] mon is  taheo125
2017-06-13 10:08:12,914 INFO monitors.py [line:56] execute command is sudo -i stop ceph-mon id=taheo125 & sleep 5
2017-06-13 10:08:18,100 ERROR monitors.py [line:61] Error when shutdown mon taheo125
2017-06-13 10:08:18,100 ERROR monitors.py [line:62] sudo -i stop ceph-mon id=taheo125 & sleep 5
2017-06-13 10:08:18,100 ERROR monitors.py [line:63] tdin: is not a tty
stop: Unknown instance: ceph/taheo125

2017-06-13 10:08:18,100 INFO monitors.py [line:68] mon is  taheo125
2017-06-13 10:08:18,100 INFO monitors.py [line:69] execute command is sudo -i ceph-mon -i taheo125 & sleep 30
2017-06-13 10:08:48,285 ERROR monitors.py [line:75] Error when start mon taheo125
2017-06-13 10:08:48,286 ERROR monitors.py [line:76] sudo -i ceph-mon -i taheo125 & sleep 30
2017-06-13 10:08:48,286 ERROR monitors.py [line:77] tdin: is not a tty
2017-06-13 10:08:21.920380 7fb171b8b4c0 -1 asok(0x7fb16e1351c0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-mon.taheo125.asok': (17) File exists
IO error: lock /var/lib/ceph/mon/ceph-taheo125/store.db/LOCK: Resource temporarily unavailable
2017-06-13 10:08:21.930567 7fb171b8b4c0 -1 error opening mon data directory at '/var/lib/ceph/mon/ceph-taheo125': (22) Invalid argument

2017-06-13 10:08:48,536 INFO monitors.py [line:45] ['enali   48475 48462  0 10:08 ?        00:00:00 bash -c ps -ef | grep ceph-mon', 'denali   48477 48475  0 10:08 ?        00:00:00 grep ceph-mon', 'root     53277     1  2 09:43 ?        00:00:38 ceph-mon -i taheo125', '']
2017-06-13 10:08:48,536 INFO monitors.py [line:51] mon pid is 53277
2017-06-13 10:08:48,537 INFO monitors.py [line:92] execute command is sudo -i kill -9 53277 & sleep 3
2017-06-13 10:14:22,328 INFO monitors.py [line:126] tdin: is not a tty
2017-06-13 10:14:25.862235 7f532d2a5700  0 monclient(hunting): authenticate timed out after 300
2017-06-13 10:14:25.862281 7f532d2a5700  0 librados: client.admin authentication error (110) Connection timed out
Error connecting to cluster: TimedOut

2017-06-13 10:14:22,328 INFO monitors.py [line:129] tdin: is not a tty
2017-06-13 10:14:22,328 INFO monitors.py [line:129] 2017-06-13 10:14:25.862235 7f532d2a5700  0 monclient(hunting): authenticate timed out after 300
2017-06-13 10:14:22,328 INFO monitors.py [line:129] 2017-06-13 10:14:25.862281 7f532d2a5700  0 librados: client.admin authentication error (110) Connection timed out
2017-06-13 10:14:22,328 INFO monitors.py [line:129] Error connecting to cluster: TimedOut
2017-06-13 10:14:22,328 INFO monitors.py [line:129] 
2017-06-13 10:14:22,329 INFO TC57_kill_lead_mon_on_multiMon.py [line:67] now the leader mon is None
2017-06-13 10:14:22,542 INFO monitors.py [line:45] ['enali   51526 51525  0 10:14 ?        00:00:00 bash -c ps -ef | grep ceph-mon', 'denali   51528 51526  0 10:14 ?        00:00:00 grep ceph-mon', '']
2017-06-13 10:14:22,542 INFO monitors.py [line:51] mon pid is 53277
2017-06-13 10:14:22,542 INFO monitors.py [line:92] execute command is sudo -i kill -9 53277 & sleep 3
